### ISSUE TITLE
[ReactNative] this.virtualRenderer not always initialized in RecyclerListView

### ISSUE THREAD

**Issue by peterjuras** [Flipkart/ReactEssentials#40] opened 2017-09-07 15:55 UTC
First of all, thanks a lot for creating this great list view component. The built in FlatList and SectionList components of react-native are pretty bad at handling initial scrollOffsets, where this component really shines (especially with ContextProvider).

I found a bug where new props lead to exceptions through the componentWillReceiveProps call in RecyclerListView:

When the RecyclerListViews parent is re-rendered early after being mounted, the RecyclerListView's componentWillReceiveProps is called, but this.virtualizedRenderer is not yet initialized. This will lead to two exceptions in the following lines:

- [RecyclerListView.js line 193](https://github.com/Flipkart/ReactEssentials/blob/recyclerlistview-master/src/recyclerlistview/RecyclerListView.js#L193)
- [RecyclerListView.js line 88](https://github.com/Flipkart/ReactEssentials/blob/recyclerlistview-master/src/recyclerlistview/RecyclerListView.js#L88)

As a quick fix, I wrapped both lines in an `if (this.virtualRenderer) { ... }` and there are no more exceptions or weird behavior.

You can try out the following sample to reproduce the bug:

[Sample Repo](https://github.com/peterjuras/recyclerview-receiveprops-demo)

**Comment by peterjuras** [comment] 2017-09-07 21:46
I think the following line suffers from the same issue (I also get an exception because this._virtualRenderer is null):

- [RecyclerListView.js line 183](https://github.com/Flipkart/ReactEssentials/blob/recyclerlistview-master/src/recyclerlistview/RecyclerListView.js#L183)

**Comment by naqvitalha** [comment] 2017-09-08 07:54
This usually sometimes happens on dev mode where the time to mount is huge. Never saw in prod mode. If you have a fix can you raise a PR otherwise we'll pick it up when we have time available.

**Comment by naqvitalha** [comment] 2017-09-08 07:54
And thanks for the feedback, really appreciate it!

**Comment by AbdallaMohamed** [comment] 2017-09-19 10:48
I'm seeing the same error when I try to call `scrollToIndex` in my `componentDidMount` lifecycle hook. The problem, as far as I could investigate, is that `_initTrackers` is not called until `_onSizeChanged` is called.
@naqvitalha Could you elaborate?

**Comment by naqvitalha** [comment] 2017-09-19 11:25
@AbdallaMohamed You are right, it's not safe to call it in componentDidMount because initialisation might not have happened. But for your specific use case I think you can specify `initialScrollIndex`. It was designed for such use cases.

**Comment by AbdallaMohamed** [comment] 2017-09-19 16:22
@naqvitalha that was my first approach but because I'm fetching data from an API, the scroll position is lost. That's the same issue here https://github.com/Flipkart/ReactEssentials/issues/44

**Comment by naqvitalha** [comment] 2017-09-20 10:35
Why don't you render RecyclerListView once you have the data? Get data and create data source post that render RecyclerListView with initialRenderIndex. For initialRenderIndex to work you need data to be present. Anyways, can you elaborate on the use case so that I can assist better?

**Comment by AbdallaMohamed** [comment] 2017-09-21 09:33
Even if I rendered the RecyclerListView after I load the data. I'd still have to imperatively scroll to the desired index, which will break because of #44. Thanks for the suggestion though.

**Comment by naqvitalha** [comment] 2017-09-25 07:17
@peterjuras Have raised a PR to fix this issue https://github.com/Flipkart/ReactEssentials/pull/46 . Tested on your sample as well. Can you once go through and verify if it fixes the issues you encountered. We will then publish the package.

**Comment by naqvitalha** [comment] 2017-09-25 07:20
@AbdallaMohamed scrollToIndex will still fail if called before mounting. I believe that's the way it should be and currently we don't have a workaround. I will put a null check though.

**Comment by AbdallaMohamed** [comment] 2017-09-25 07:28
@naqvitalha Yeah. I put a `setTimeout` as a workaround. I think it all comes to maintaining the scroll position as new items are added to the list. Then there would be no need to call `scrollToIndex`, because we already have`initialRenderIndex`

**Comment by naqvitalha** [comment] 2017-09-25 08:14
@AbdallaMohamed Interested in seeing what you're building. Anyway to take a look?

**Comment by naqvitalha** [comment] 2017-09-26 09:05
Fixed in https://github.com/Flipkart/ReactEssentials/pull/46

**Closed by naqvitalha** 2017-09-26 09:05 UTC

**Comment by peterjuras** [comment] 2017-09-27 09:28
Sorry for the late response, I can confirm that the fix resolves the issue.

However, you should check out #47 since it might affect new users.

**Comment by AbdallaMohamed** [comment] 2017-09-27 19:19
@naqvitalha can you share your email so I could share the details with you? I tried sending an email to cross-platform@flipkart.com but Gmail fails to deliver my mails.

**Comment by naqvitalha** [comment] 2017-09-28 09:24
cross-platform@flipkart.com is public now... it should be working... can you try now? If it doesn't please DM me on twitter.. I'll pass on the email there.
